language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - build-tools-26.0.2
    - platform-tools
    - android-26
    - extra
  licenses:
    - '.+'

before_script:
  - chmod +x gradlew

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

script:
  - ./gradlew dependencies
  - ./gradlew assembleDebug